version: "3.8"
services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: temi-mqtt-broker
    restart: unless-stopped
    ports:
      - "1884:1884"
      - "9003:9003"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./password.txt:/mosquitto/config/password.txt
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

volumes:
  mosquitto_data:
  mosquitto_log:
